import numpy as np
from scipy.spatial import ConvexHull, QhullError

def is_octahedral(points):
    """
    Return True iff the convex hull of 6 points in R^3
    is combinatorially equivalent to an octahedron.

    Generated by chatGPT:
    """
    X = np.asarray(points, dtype=float)

    if X.shape != (6, 3):
        raise ValueError("points must have shape (6, 3)")

    try:
        hull = ConvexHull(X)
    except QhullError:
        return False

    # All 6 points must actually be hull vertices
    if len(hull.vertices) != 6:
        return False

    # Build edge set from triangular hull facets
    edges = set()
    for tri in hull.simplices:
        a, b, c = tri
        edges.update({
            tuple(sorted((a, b))),
            tuple(sorted((a, c))),
            tuple(sorted((b, c))),
        })

    # Degree of each vertex in the hull graph
    deg = np.zeros(6, dtype=int)
    for i, j in edges:
        deg[i] += 1
        deg[j] += 1

    # Octahedron graph on 6 vertices is the unique 4-regular graph
    return np.all(deg == 4), edges